#!/bin/bash

set -Eeuo pipefail

usage() {
    cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-c] [folder]

This script encrypts a folder/archive using age (https://github.com/FiloSottile/age).
Uses AGE_PUB specified in ./crc to preform RSA-hybrid encrption
ex. age-encrypt ./test

Available options:

-h, --help      Print this help and exit
-v, --verbose   Print script debug info
-c, --symmetric Use symmetric encryption
EOF
    exit
}


encrypt_folder() {
    # Encrypt Folder (and possible save over)
    local FOLDER=${1:-$(</dev/stdin)} # /path/to/earchive.tar.gpg
    local FILE="$FOLDER.tar.age"

    local AGE_E
    if $AGE_SYMMETRIC; then
        AGE_E="age -e -p"
    else
        AGE_E="age -e -R $AGE_PUB"
    fi

    # Now Encrypt opened folder
    tar -cC $FOLDER . | zstd -z -19 -T0 - | $AGE_E > $FILE
}


parse_params() {
    # default values of variables set from params
    local AGE_SYMMETRIC=false
    while :; do
        case "${1-}" in
            -h | --help)
                usage ;;
            -v | --verbose)
                set -x ;;
            -c | --symmetric)
                AGE_SYMMETRIC=true ;;
            -?*) die "Unknown option: $1" ;;
            *) break ;;
        esac
        shift
    done

    # Parse file
    FULL_PATH="${@:$#}" #This is the input for stuff

    # Encrypt Folder
    encrypt_folder $FULL_PATH #$AGE_SYMMETRIC
    return 0
}


#MAIN RUNNER
if [ $# -eq 0 ]; then
    usage
else
    parse_params $@
fi

exit